FROM ubuntu:22.04

RUN apt update
RUN apt upgrade

RUN apt install -y build-essential
RUN apt install -y cmake
RUN apt install -y cppcheck
RUN apt install -y clang lldb llvm
RUN apt install -y valgrind gdb
RUN apt install -y git
